#!/bin/sh
case "${1-}" in
	'pre')
		exec rc-service intel-undervolt stop
	;;

	'post')
		exec rc-service intel-undervolt start
	;;

	*)
		exit 64
	;;
esac

#this is in case that intel-undervolt wont start after resuming from sleep
#if you use a different init system, adjust the openrc-commansds accordingly
#replace /usr/lib/elogind/system-sleep/*-intel-undervolt with this one
